// Generated by CoffeeScript 1.3.3
(function() {

  (function($) {
    return $.fn.filtermenu = function(opts) {
      var settings, table;
      settings = $.extend({
        columns: [1],
        bodyId: "",
        bodyIndex: 0,
        headIndex: 0,
        resetValue: "##FILTERMENU.RESET##",
        curFilters: []
      }, opts);
      table = this;
      $.each(settings.columns, function(index, curCol) {
        var body, buildSelect, col, firstRun, head, rebuild, select, unfiltered;
        body = table.find("tbody" + settings.bodyId).eq(settings.bodyIndex);
        head = table.find("thead").eq(settings.headIndex);
        select = $("<select/>");
        col = ":nth-child(" + curCol + ")";
        firstRun = true;
        unfiltered = function(cCol) {
          return $.each(settings.curFilters, function(index, item) {
            return item.column !== cCol;
          });
        };
        buildSelect = function(selector) {
          var box, firstOpt, intCol, itemsArray;
          intCol = selector.replace(/\D/g, "");
          itemsArray = [];
          box = head.find("tr>*" + selector).find("select");
          if (box.length === 0) {
            box = select.clone(true);
          } else {
            box.detach();
            box = select.clone(true);
          }
          box.addClass("FilterColumn_" + intCol);
          body.find("tr>td" + selector).filter(":visible").each(function() {
            if (firstRun) {
              $(this).addClass("FilterColumn_" + curCol);
            }
            return itemsArray.push($(this).text());
          });
          firstRun = false;
          firstOpt = $("<option />", {
            value: settings.resetValue,
            text: "Choose Filter"
            /*
                    if unfiltered intCol
                      firstOpt.text "Choose Filter"
                    else
                      firstOpt.text "Remove Filter"
            */

          });
          box.append(firstOpt);
          itemsArray = $.grep(itemsArray, function(el, index) {
            return index === $.inArray(el, itemsArray);
          });
          $.each(itemsArray, function(index, item) {
            var curOpt;
            curOpt = $("<option />", {
              value: item
            });
            if (($.trim(item) != null) && $.trim(item) !== "") {
              curOpt.text(item);
            } else {
              curOpt.text("None");
            }
            return box.append(curOpt);
          });
          box.prop("selectedIndex", 1);
          return head.find("tr>*" + selector).each(function() {
            var selectBox;
            selectBox = box.clone(true);
            return $(this).append(selectBox);
          });
        };
        rebuild = function(c) {
          return $.each($.grep(settings.columns, function(el, index) {
            return unfiltered("" + el);
          }), function(index, item) {
            return buildSelect(":nth-child(" + item + ")");
          });
        };
        select.change(function(evt) {
          var cColumn, chk, clearLink, sBox, selector;
          sBox = $(this);
          chk = sBox.val();
          cColumn = sBox.attr("class").replace(/\D/g, "");
          selector = ":nth-child(" + cColumn + ")";
          sBox.hide();
          if (chk !== settings.resetValue) {
            settings.curFilters.push({
              column: cColumn,
              value: chk
            });
            body.find("tr").filter(":visible").filter(function(i) {
              return $(this).find("td" + selector).text() !== chk;
            }).hide();
            clearLink = $("<a>", {
              text: "(" + chk + ")"
            });
            clearLink.css({
              display: "block"
            });
            clearLink.click(function() {
              var popFilter;
              $(this).remove();
              popFilter = settings.curFilters.splice(settings.curFilters.indexOf({
                column: cColumn,
                value: chk
              }), 1);
              if (settings.curFilters.length !== 0) {
                body.find("tr").filter(":hidden").filter(function(i) {
                  var row, win;
                  row = $(this);
                  return win = $.each(settings.curFilters, function(index, item) {
                    console.log(row.find("td:nth-child(" + item.column + ")"));
                    console.log("checking to see if " + ($.trim(row.find("td:nth-child(" + item.column + ")").text())) + " is " + ($.trim(item.value)));
                    win = $.trim($(this).find("td:nth-child(" + item.column + ")").text()) === $.trim(item.value);
                    return console.log(win);
                  });
                }).show();
              } else {
                body.find("tr").filter(":hidden").show();
              }
              return sBox.show();
            });
            clearLink.appendTo(sBox.parent());
            return rebuild(cColumn);
          }
        });
        return buildSelect(col);
      });
      return this;
    };
  })(jQuery);

}).call(this);
